### ISSUE TITLE
Index out of range: index should be less than 272: 272

### ISSUE THREAD

**Issue by divyanshub024** [brendan-duncan/archive#122]
I'm getting `Index out of range` error when calling `archive.first.content`.

## Logs

```
E/flutter (14180): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 272: 272
E/flutter (14180): #0      Uint8List.[]= (dart:typed_data-patch/typed_data_patch.dart:2225:7)
E/flutter (14180): #1      Inflate._decode (package:archive/src/zlib/inflate.dart:317:20)
E/flutter (14180): #2      Inflate._parseDynamicHuffmanBlock (package:archive/src/zlib/inflate.dart:231:9)
E/flutter (14180): #3      Inflate._parseBlock (package:archive/src/zlib/inflate.dart:117:9)
E/flutter (14180): #4      Inflate._inflate (package:archive/src/zlib/inflate.dart:87:20)
E/flutter (14180): #5      new Inflate.buffer (package:archive/src/zlib/inflate.dart:19:5)
E/flutter (14180): #6      ArchiveFile.decompress (package:archive/src/archive_file.dart:71:28)
E/flutter (14180): #7      ArchiveFile.content (package:archive/src/archive_file.dart:62:7)
E/flutter (14180): #8      _HomePageState.postData (package:offline_kyc/home_page.dart:174:39)
E/flutter (14180): <asynchronous suspension>
E/flutter (14180): #9      _HomePageState.build.<anonymous closure> (package:offline_kyc/home_page.dart:112:13)
E/flutter (14180): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (14180): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (14180): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (14180): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (14180): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (14180): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (14180): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (14180): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (14180): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (14180): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14180): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (14180): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (14180): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (14180): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (14180): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (14180): #25     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (14180): #26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (14180): #27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (14180): #28     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14180): #29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14180): #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14180): #31     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (14180): #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (14180): 

```

## code

```
Archive archive = ZipDecoder().decodeBytes(zipBytes, password: '1234');

    var archiveFile = archive.first;
    String filename = archiveFile.name;
    print('FileNAme: $filename');
    print('isComressed: ${archiveFile.isCompressed}');
    var content = archive.first.content;
    print('archive: $content');
```

**Comment by pravindahal** [comment]
I encountered the same issue so I am providing more information which may be useful to debug this issue.

## data

`data.bin.base64encoded.txt`:
```base64
rJhLb+M2EMe/ymKulRySIvW6pUmANlug3eyiPQSBQIt0IkSWDT3SBoG/e0HJkumYZqh9HALtgP
nN/Icz5DBvIHjLIf30BoWAFG5vr79++esKPMh5LRpI3wBDWnVl6QHp/xeony+87CSkOPBAFM22
5K/Z3gSX4MGK5+qz2XIhwYOm5W3XQApqoRSw8wDHOiY+xYQHjCj4elMJM4hgDUTwKShxBTEdxE
5Bn11BkQ6KTkHkAMrLbmmmBHqeA0OeYycK1SnUmp33lKJ64lVPoUSjUHJKoQfKk+R1aw6G6pKo
QRKzYLRodE2UWkvHgtG3m1khJ2WsQfTMMGLtBktm9GaIrZt0Nha12WOj0uFj50Hb1RWkRHdabx
5r2TT7Ds9queZFVVSPkOLEg7yra1m1WQ8dmv9QP9iapnP1s/Og3nQKxzxo8k0tM+V5ovc/cl6W
kAYePG5aSMluf9ocm+kgcjSTvRnvesmjOdqbw91IMXgIzB7CYw/Y7OEAGZfj0995p4HuzezYgy
6NmiCjHZt1GzyE5iwFxx6IroGd8YDMWUJmDcicJbRTLvpir5vJkbptsAcVX6vauds8Fe2nr91S
igI8KJqM523xIiFt6056IORLkcusv6KukvgmvA4T/zphNz4NyaWfxCjwo18TRCN0FaPgZmAslf
sBsC3yrKtLSAE86BpZDyzwoORNO3kDggj2EfVR+A2jlJCUBguEMEbkF0RShFSBy0pk+Wa97dto
z1eNlq2LpsnyTVft95mMQskk9Nvvv/1595FCLfoVL5sfDZ+wJApnhj9tsfITTOHf1EX1UfQxSc
IV48KnDK18ijnxeYQDn+FAEJrglYjlz9ufgC0YimhEvkMgHQXSSeBnXsqPBC7jOBQrhH2MMfEp
TiKfL+OVL5jAiGIqaLT6iQKjBcIhnS1vPHazpuV1K0W2fO07bjD+W1SVrHvD0JnKMnbn/f0PTF
TT5XhgGO5FjGZC1OX0HhLNDcQwc9w6MR68++8dxk7DCJB19HEAhFYdDoDEOqmcA+hZoFYN50em
AyC0pvH85HYgJNY0uBBmzrJTIh76w13rk8AKckjH3KfUKSGxd5lLDNa3ylnAUVkYGMG8PWHWRn
chIKsOB8LcSV6vi+D4/Jz3/jOcWdZ8OmwqSayl6RBBbA3h7GHx0F+wei5Ca1adjvDQWhwuNc6s
atzukdl/HTC1yvy/ehgiMRzDX2YyIus57JJSaq1xWzoe1Bt10/Iy68eSpn8jDob+pbgfSHy0iJ
Pjf/0BjOki6juOLkhfbT5aRMfr4p0H47Cjpq3hOyuUr+G17PIAYHGCpwlsPzAJyUv9ETtMYmT8
CMYPOnxoj9GPVwbOK6nzSua4cueBeK34usizsqie1XnXttsmvbhQwhfqcbesJX9eVLK9kOyP10
vOrgn7++4f8SxUP9ddKftRUhRNP5NuqkwWj0/TLCz/a2uurFVRydHr7v8AAAD//w==
```

```shell
base64 -d < data.bin.base64encoded.txt > data.bin
```

## dart

`bin/archive_bug.dart`:
```dart
import 'dart:io';
import 'dart:convert';

import 'package:archive/archive.dart' as archive;

void main(List<String> arguments) async {

  dynamic response;
  try {
    final file = File('data.bin');
    final data = await file.readAsBytes();
    final inflatedDataBytes = archive.Inflate(data).getBytes();
    final inflatedDataString = utf8.decode(inflatedDataBytes);
    response = jsonDecode(inflatedDataString);
  } catch (e) {
    print(e);
  }
  print(response);
}
```

`pubspec.yaml`:
```yaml
name: archive_bug
description: A cli example to demonstrate a potential bug in archive package.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.1.2

dev_dependencies:
  pedantic: ^1.9.0
```

Run:
```shell
dart pub get
dart run bin/archive_bug.dart
```

Output:
```
RangeError (index): Index out of range: index should be less than 278: 278
null
```

## golang

`main.go`:
```go
package main

import (
	"bytes"
	"compress/flate"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	data, err := ioutil.ReadFile("data.bin")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Decompressed output")
	zr := flate.NewReader(bytes.NewReader(data))
	if _, err := io.Copy(os.Stdout, zr); err != nil {
		log.Fatal(err)
	}
	if err := zr.Close(); err != nil {
		log.Fatal(err)
	}

	fmt.Println()

}
```

Run:
```shell
go version
go run main.go
```

Output:
```json
{"data": {"id":"JJDSQPC","cards":{"1":null,"2":{"13":{"value":13,"display_value":"A","face":"spade","status":"played"},"18":{"value":18,"display_value":"6","face":"diamond","status":"played"},"21":{"value":21,"display_value":"9","face":"diamond","status":"played"},"25":{"value":25,"display_value":"K","face":"diamond","status":"played"},"27":{"value":27,"display_value":"2","face":"club","status":"played"},"33":{"value":33,"display_value":"8","face":"club","status":"played"},"34":{"value":34,"display_value":"9","face":"club","status":"inhand"},"42":{"value":42,"display_value":"4","face":"heart","status":"played"},"43":{"value":43,"display_value":"5","face":"heart","status":"inhand"},"44":{"value":44,"display_value":"6","face":"heart","status":"inhand"},"5":{"value":5,"display_value":"6","face":"spade","status":"inhand"},"52":{"value":52,"display_value":"A","face":"heart","status":"played"},"8":{"value":8,"display_value":"9","face":"spade","status":"inhand"}},"3":null,"4":null},"turn":2,"status":"progress","card_remaining":19,"current_hand":{"1":{"value":31,"display_value":"6","face":"club","status":"inhand"}},"round":5,"score_card":{"1":{"1":{"call":3,"got":2},"2":{"call":3,"got":4},"3":{"call":2,"got":1},"4":{"call":7,"got":6}},"2":{"1":{"call":3,"got":3},"2":{"call":3,"got":6},"3":{"call":1,"got":1},"4":{"call":3,"got":3}},"3":{"1":{"call":1,"got":2},"2":{"call":4,"got":5},"3":{"call":3,"got":4},"4":{"call":1,"got":2}},"4":{"1":{"call":2,"got":1},"2":{"call":4,"got":6},"3":{"call":2,"got":3},"4":{"call":2,"got":3}},"5":{"1":{"call":2,"got":0},"2":{"call":3,"got":0},"3":{"call":3,"got":0},"4":{"call":3,"got":0}}},"players":{"1":{"id":1,"name":"Rohit Subedi","is_active":true,"device_id":"C98E6D69-D95E-462A-9803-7B90470C803E","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.001102+02:00","send_compress":true,"turn_miss_count":5},"2":{"id":2,"name":"TIHOR","is_active":true,"device_id":"","is_bot":false,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.025976+02:00","send_compress":true,"turn_miss_count":0},"3":{"id":3,"name":"Erin","is_active":true,"device_id":"8296f5ad-450f-41a2-a713-513d2491fd8e","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:35.507472+02:00","send_compress":true,"turn_miss_count":0},"4":{"id":4,"name":"Kale","is_active":true,"device_id":"b886df01-1112-4197-ab8f-d5d10414d47f","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:37.0164+02:00","send_compress":true,"turn_miss_count":0}},"round_started_by":1,"round_winner":1,"player_wins":{"1":[[{"value":21,"display_value":"9","face":"diamond","status":"inhand"},{"value":22,"display_value":"10","face":"diamond","status":"inhand"},{"value":19,"display_value":"7","face":"diamond","status":"inhand"},{"value":23,"display_value":"J","face":"diamond","status":"inhand"}],[{"value":33,"display_value":"8","face":"club","status":"inhand"},{"value":30,"display_value":"5","face":"club","status":"inhand"},{"value":36,"display_value":"J","face":"club","status":"inhand"},{"value":39,"display_value":"A","face":"club","status":"inhand"}],[{"value":4,"display_value":"5","face":"spade","status":"inhand"},{"value":46,"display_value":"8","face":"heart","status":"inhand"},{"value":49,"display_value":"J","face":"heart","status":"inhand"},{"value":42,"display_value":"4","face":"heart","status":"inhand"}]],"2":[[{"value":3,"display_value":"4","face":"spade","status":"inhand"},{"value":13,"display_value":"A","face":"spade","status":"inhand"},{"value":9,"display_value":"10","face":"spade","status":"inhand"},{"value":1,"display_value":"2","face":"spade","status":"inhand"}],[{"value":41,"display_value":"3","face":"heart","status":"inhand"},{"value":45,"display_value":"7","face":"heart","status":"inhand"},{"value":40,"display_value":"2","face":"heart","status":"inhand"},{"value":52,"display_value":"A","face":"heart","status":"inhand"}]],"3":[[{"value":27,"display_value":"2","face":"club","status":"inhand"},{"value":2,"display_value":"3","face":"spade","status":"inhand"},{"value":29,"display_value":"4","face":"club","status":"inhand"},{"value":28,"display_value":"3","face":"club","status":"inhand"}]],"4":[[{"value":26,"display_value":"A","face":"diamond","status":"inhand"},{"value":6,"display_value":"7","face":"spade","status":"inhand"},{"value":15,"display_value":"3","face":"diamond","status":"inhand"},{"value":25,"display_value":"K","face":"diamond","status":"inhand"}],[{"value":18,"display_value":"6","face":"diamond","status":"inhand"},{"value":24,"display_value":"Q","face":"diamond","status":"inhand"},{"value":7,"display_value":"8","face":"spade","status":"inhand"},{"value":14,"display_value":"2","face":"diamond","status":"inhand"}]]},"total_rounds":5,"total_score":{"1":-0.8999999999999999,"2":14.7,"3":4.2,"4":-0.7999999999999998},"winner":"","winner_ids":null,"last_active":"2021-04-06T10:22:43.005891+02:00","player_deal":{"1":{"1":true,"2":true,"3":true,"4":true},"2":{"1":true,"2":true,"3":true,"4":true},"3":{"1":true,"2":true,"3":true,"4":true},"4":{"1":true,"2":true,"3":true,"4":true},"5":{"1":true,"2":true,"3":true,"4":true}},"dynamic_link":"https://play.callbreak.net/e5LyAa5D25VRWdkdA","rules":{"dismiss_on_eight":true,"extra_on_nine":true}}}
```

## node

`main.js`:
```javascript
'use strict'

const zlib = require('zlib')
const fs = require('fs/promises')
const util = require('util')
const inflateRaw = util.promisify(zlib.inflateRaw)


const main = async () => {
    const contents = await fs.readFile("data.bin")
    const contentsInflated = await inflateRaw(contents)
    console.log(contentsInflated.toString('utf8'))
}

main().then(() => {
    //console.log("success")
})
```

Run:
```
nvm install 15.13.0
nvm use 15.13.0

node main.js
```

Output:
```json
{"data": {"id":"JJDSQPC","cards":{"1":null,"2":{"13":{"value":13,"display_value":"A","face":"spade","status":"played"},"18":{"value":18,"display_value":"6","face":"diamond","status":"played"},"21":{"value":21,"display_value":"9","face":"diamond","status":"played"},"25":{"value":25,"display_value":"K","face":"diamond","status":"played"},"27":{"value":27,"display_value":"2","face":"club","status":"played"},"33":{"value":33,"display_value":"8","face":"club","status":"played"},"34":{"value":34,"display_value":"9","face":"club","status":"inhand"},"42":{"value":42,"display_value":"4","face":"heart","status":"played"},"43":{"value":43,"display_value":"5","face":"heart","status":"inhand"},"44":{"value":44,"display_value":"6","face":"heart","status":"inhand"},"5":{"value":5,"display_value":"6","face":"spade","status":"inhand"},"52":{"value":52,"display_value":"A","face":"heart","status":"played"},"8":{"value":8,"display_value":"9","face":"spade","status":"inhand"}},"3":null,"4":null},"turn":2,"status":"progress","card_remaining":19,"current_hand":{"1":{"value":31,"display_value":"6","face":"club","status":"inhand"}},"round":5,"score_card":{"1":{"1":{"call":3,"got":2},"2":{"call":3,"got":4},"3":{"call":2,"got":1},"4":{"call":7,"got":6}},"2":{"1":{"call":3,"got":3},"2":{"call":3,"got":6},"3":{"call":1,"got":1},"4":{"call":3,"got":3}},"3":{"1":{"call":1,"got":2},"2":{"call":4,"got":5},"3":{"call":3,"got":4},"4":{"call":1,"got":2}},"4":{"1":{"call":2,"got":1},"2":{"call":4,"got":6},"3":{"call":2,"got":3},"4":{"call":2,"got":3}},"5":{"1":{"call":2,"got":0},"2":{"call":3,"got":0},"3":{"call":3,"got":0},"4":{"call":3,"got":0}}},"players":{"1":{"id":1,"name":"Rohit Subedi","is_active":true,"device_id":"C98E6D69-D95E-462A-9803-7B90470C803E","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.001102+02:00","send_compress":true,"turn_miss_count":5},"2":{"id":2,"name":"TIHOR","is_active":true,"device_id":"","is_bot":false,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.025976+02:00","send_compress":true,"turn_miss_count":0},"3":{"id":3,"name":"Erin","is_active":true,"device_id":"8296f5ad-450f-41a2-a713-513d2491fd8e","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:35.507472+02:00","send_compress":true,"turn_miss_count":0},"4":{"id":4,"name":"Kale","is_active":true,"device_id":"b886df01-1112-4197-ab8f-d5d10414d47f","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:37.0164+02:00","send_compress":true,"turn_miss_count":0}},"round_started_by":1,"round_winner":1,"player_wins":{"1":[[{"value":21,"display_value":"9","face":"diamond","status":"inhand"},{"value":22,"display_value":"10","face":"diamond","status":"inhand"},{"value":19,"display_value":"7","face":"diamond","status":"inhand"},{"value":23,"display_value":"J","face":"diamond","status":"inhand"}],[{"value":33,"display_value":"8","face":"club","status":"inhand"},{"value":30,"display_value":"5","face":"club","status":"inhand"},{"value":36,"display_value":"J","face":"club","status":"inhand"},{"value":39,"display_value":"A","face":"club","status":"inhand"}],[{"value":4,"display_value":"5","face":"spade","status":"inhand"},{"value":46,"display_value":"8","face":"heart","status":"inhand"},{"value":49,"display_value":"J","face":"heart","status":"inhand"},{"value":42,"display_value":"4","face":"heart","status":"inhand"}]],"2":[[{"value":3,"display_value":"4","face":"spade","status":"inhand"},{"value":13,"display_value":"A","face":"spade","status":"inhand"},{"value":9,"display_value":"10","face":"spade","status":"inhand"},{"value":1,"display_value":"2","face":"spade","status":"inhand"}],[{"value":41,"display_value":"3","face":"heart","status":"inhand"},{"value":45,"display_value":"7","face":"heart","status":"inhand"},{"value":40,"display_value":"2","face":"heart","status":"inhand"},{"value":52,"display_value":"A","face":"heart","status":"inhand"}]],"3":[[{"value":27,"display_value":"2","face":"club","status":"inhand"},{"value":2,"display_value":"3","face":"spade","status":"inhand"},{"value":29,"display_value":"4","face":"club","status":"inhand"},{"value":28,"display_value":"3","face":"club","status":"inhand"}]],"4":[[{"value":26,"display_value":"A","face":"diamond","status":"inhand"},{"value":6,"display_value":"7","face":"spade","status":"inhand"},{"value":15,"display_value":"3","face":"diamond","status":"inhand"},{"value":25,"display_value":"K","face":"diamond","status":"inhand"}],[{"value":18,"display_value":"6","face":"diamond","status":"inhand"},{"value":24,"display_value":"Q","face":"diamond","status":"inhand"},{"value":7,"display_value":"8","face":"spade","status":"inhand"},{"value":14,"display_value":"2","face":"diamond","status":"inhand"}]]},"total_rounds":5,"total_score":{"1":-0.8999999999999999,"2":14.7,"3":4.2,"4":-0.7999999999999998},"winner":"","winner_ids":null,"last_active":"2021-04-06T10:22:43.005891+02:00","player_deal":{"1":{"1":true,"2":true,"3":true,"4":true},"2":{"1":true,"2":true,"3":true,"4":true},"3":{"1":true,"2":true,"3":true,"4":true},"4":{"1":true,"2":true,"3":true,"4":true},"5":{"1":true,"2":true,"3":true,"4":true}},"dynamic_link":"https://play.callbreak.net/e5LyAa5D25VRWdkdA","rules":{"dismiss_on_eight":true,"extra_on_nine":true}}}
```

**Comment by brendan-duncan** [comment]
I assume go and node are both using zlib for their inflate. I'll have to dig into what extra error checking and compensation zlib is doing. I checked the bin file with a different inflate implementation and it also errored with an invalid huffman block. So there's definitely something wrong with the data, but there's probably a better way of compensating for the error.

**Comment by brendan-duncan** [comment]
I checked ZLib, and it says there's a data error, too. The reason why it's "working" is because it's writing out the output it got before the error. I'll look into adding that behavior to this library.

**Comment by pravindahal** [comment]
I experimented some more and this may be useful:

[archive_bug.zip](https://github.com/brendan-duncan/archive/files/6272144/archive_bug.zip)

I was able to re-create the problematic deflated data using the `compress` golang package https://golang.org/pkg/compress/flate/ (https://github.com/klauspost/compress). It is the same package I used to deflate the data in the example in my previous comment.

If you think the bug in that package, I can report it there. Please let me know.

`compress.go`:
```go
package main

import (
	"bytes"
	"compress/flate"
	"fmt"
	"io/ioutil"
	"log"
)

func main() {
	data, err := ioutil.ReadFile("data.json")
	if err != nil {
		log.Fatal(err)
	}
	buffer := bytes.Buffer{}
	writer, err := flate.NewWriter(&buffer, 9)
	if err == nil {
		writer.Write(data)
		writer.Close()
		data = buffer.Bytes()
	}
	ioutil.WriteFile("data-problematic.bin", data, 0755)
	fmt.Println(`Output written to "data-problematic.bin"`)
}
```

`data.json`:
```json
{"data": {"id":"JJDSQPC","cards":{"1":null,"2":{"13":{"value":13,"display_value":"A","face":"spade","status":"played"},"18":{"value":18,"display_value":"6","face":"diamond","status":"played"},"21":{"value":21,"display_value":"9","face":"diamond","status":"played"},"25":{"value":25,"display_value":"K","face":"diamond","status":"played"},"27":{"value":27,"display_value":"2","face":"club","status":"played"},"33":{"value":33,"display_value":"8","face":"club","status":"played"},"34":{"value":34,"display_value":"9","face":"club","status":"inhand"},"42":{"value":42,"display_value":"4","face":"heart","status":"played"},"43":{"value":43,"display_value":"5","face":"heart","status":"inhand"},"44":{"value":44,"display_value":"6","face":"heart","status":"inhand"},"5":{"value":5,"display_value":"6","face":"spade","status":"inhand"},"52":{"value":52,"display_value":"A","face":"heart","status":"played"},"8":{"value":8,"display_value":"9","face":"spade","status":"inhand"}},"3":null,"4":null},"turn":2,"status":"progress","card_remaining":19,"current_hand":{"1":{"value":31,"display_value":"6","face":"club","status":"inhand"}},"round":5,"score_card":{"1":{"1":{"call":3,"got":2},"2":{"call":3,"got":4},"3":{"call":2,"got":1},"4":{"call":7,"got":6}},"2":{"1":{"call":3,"got":3},"2":{"call":3,"got":6},"3":{"call":1,"got":1},"4":{"call":3,"got":3}},"3":{"1":{"call":1,"got":2},"2":{"call":4,"got":5},"3":{"call":3,"got":4},"4":{"call":1,"got":2}},"4":{"1":{"call":2,"got":1},"2":{"call":4,"got":6},"3":{"call":2,"got":3},"4":{"call":2,"got":3}},"5":{"1":{"call":2,"got":0},"2":{"call":3,"got":0},"3":{"call":3,"got":0},"4":{"call":3,"got":0}}},"players":{"1":{"id":1,"name":"Rohit Subedi","is_active":true,"device_id":"C98E6D69-D95E-462A-9803-7B90470C803E","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.001102+02:00","send_compress":true,"turn_miss_count":5},"2":{"id":2,"name":"TIHOR","is_active":true,"device_id":"","is_bot":false,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:43.025976+02:00","send_compress":true,"turn_miss_count":0},"3":{"id":3,"name":"Erin","is_active":true,"device_id":"8296f5ad-450f-41a2-a713-513d2491fd8e","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:35.507472+02:00","send_compress":true,"turn_miss_count":0},"4":{"id":4,"name":"Kale","is_active":true,"device_id":"b886df01-1112-4197-ab8f-d5d10414d47f","is_bot":true,"pic_url":"","user_id":"","last_active":"2021-04-06T10:22:37.0164+02:00","send_compress":true,"turn_miss_count":0}},"round_started_by":1,"round_winner":1,"player_wins":{"1":[[{"value":21,"display_value":"9","face":"diamond","status":"inhand"},{"value":22,"display_value":"10","face":"diamond","status":"inhand"},{"value":19,"display_value":"7","face":"diamond","status":"inhand"},{"value":23,"display_value":"J","face":"diamond","status":"inhand"}],[{"value":33,"display_value":"8","face":"club","status":"inhand"},{"value":30,"display_value":"5","face":"club","status":"inhand"},{"value":36,"display_value":"J","face":"club","status":"inhand"},{"value":39,"display_value":"A","face":"club","status":"inhand"}],[{"value":4,"display_value":"5","face":"spade","status":"inhand"},{"value":46,"display_value":"8","face":"heart","status":"inhand"},{"value":49,"display_value":"J","face":"heart","status":"inhand"},{"value":42,"display_value":"4","face":"heart","status":"inhand"}]],"2":[[{"value":3,"display_value":"4","face":"spade","status":"inhand"},{"value":13,"display_value":"A","face":"spade","status":"inhand"},{"value":9,"display_value":"10","face":"spade","status":"inhand"},{"value":1,"display_value":"2","face":"spade","status":"inhand"}],[{"value":41,"display_value":"3","face":"heart","status":"inhand"},{"value":45,"display_value":"7","face":"heart","status":"inhand"},{"value":40,"display_value":"2","face":"heart","status":"inhand"},{"value":52,"display_value":"A","face":"heart","status":"inhand"}]],"3":[[{"value":27,"display_value":"2","face":"club","status":"inhand"},{"value":2,"display_value":"3","face":"spade","status":"inhand"},{"value":29,"display_value":"4","face":"club","status":"inhand"},{"value":28,"display_value":"3","face":"club","status":"inhand"}]],"4":[[{"value":26,"display_value":"A","face":"diamond","status":"inhand"},{"value":6,"display_value":"7","face":"spade","status":"inhand"},{"value":15,"display_value":"3","face":"diamond","status":"inhand"},{"value":25,"display_value":"K","face":"diamond","status":"inhand"}],[{"value":18,"display_value":"6","face":"diamond","status":"inhand"},{"value":24,"display_value":"Q","face":"diamond","status":"inhand"},{"value":7,"display_value":"8","face":"spade","status":"inhand"},{"value":14,"display_value":"2","face":"diamond","status":"inhand"}]]},"total_rounds":5,"total_score":{"1":-0.8999999999999999,"2":14.7,"3":4.2,"4":-0.7999999999999998},"winner":"","winner_ids":null,"last_active":"2021-04-06T10:22:43.005891+02:00","player_deal":{"1":{"1":true,"2":true,"3":true,"4":true},"2":{"1":true,"2":true,"3":true,"4":true},"3":{"1":true,"2":true,"3":true,"4":true},"4":{"1":true,"2":true,"3":true,"4":true},"5":{"1":true,"2":true,"3":true,"4":true}},"dynamic_link":"https://play.callbreak.net/e5LyAa5D25VRWdkdA","rules":{"dismiss_on_eight":true,"extra_on_nine":true}}}
```

`archive-bug.dart`:
```dart
import 'dart:io';
import 'dart:convert';

import 'package:archive/archive.dart' as archive;

void main(List<String> arguments) async {

  dynamic response;
  try {
    final file = File('data-problematic.bin');
    final data = await file.readAsBytes();
    final inflatedDataBytes = archive.Inflate(data).getBytes();
    final inflatedDataString = utf8.decode(inflatedDataBytes);
  } catch (e) {
    print(e);
  }
  response = jsonDecode(inflatedDataString);
  print(response);
}
```

Run:
```shell
$ go run compress.go
Output written to "data-problematic.bin"
$ dart run bin/archive-bug.dart
RangeError (index): Index out of range: index should be less than 278: 278
null
```

Thank you very much for looking into this.

**Comment by brendan-duncan** [comment]
I suspect the go library probably has a bug, writing an extra problem deflate block, or an incorrect size value. Their inflate, and zlib, more gracefully handle the error, so maybe they didn't notice. Zlib does return a -3 return value when inflating the buffer, indicating an error in the data. I still need to find some time to improve this libraries error handling in this case.

**Comment by brendan-duncan** [comment]
It will take me a while to be able to get to this. Trying to get around errors there are errors in the output. I'll have to step through zlib and see what it's doing differently than what I have. I don't know why the deflated buffer from that Go program chokes my version of deflate, I'm probably missing something. It is still strange that zlib finishes with correct looking output, but reports the data error in the check stage.

**Comment by rockingdice** [comment]
I met the same error. I handled a lot of data so I don't know where is the wrong place exactly.
Is this still an issue for this package? If so I have to consider using another plugin.

I'm using version 3.1.2

**Comment by rockingdice** [comment]
@brendan-duncan so it's quite confusing because it happened randomly. 

```
I/flutter (15561): SEVERE: 2022-07-19 08:54:23.927128: [Ropsdk] File load failed: [ht-scripts/cache.bd] RangeError (index): Index out of range: index should be less than 275: 275
I/flutter (15561): SEVERE: 2022-07-19 08:54:23.927426: #0      Uint8List.[]= (dart:typed_data-patch/typed_data_patch.dart:2229:7)
I/flutter (15561): #1      Inflate._decode
package:archive/…/zlib/inflate.dart:306
I/flutter (15561): #2      Inflate._parseDynamicHuffmanBlock
package:archive/…/zlib/inflate.dart:235
I/flutter (15561): #3      Inflate._parseBlock
package:archive/…/zlib/inflate.dart:122
I/flutter (15561): #4      Inflate._inflate
package:archive/…/zlib/inflate.dart:92
I/flutter (15561): #5      new Inflate.buffer
package:archive/…/zlib/inflate.dart:22
I/flutter (15561): #6      GZipDecoder.decodeBuffer
package:archive/src/gzip_decoder.dart:33
I/flutter (15561): #7      GZipDecoder.decodeBytes
package:archive/src/gzip_decoder.dart:18
I/flutter (15561): #8      _Encryption._decode
package:rop_sdk/private/cfg_manager.dart:791
I/flutter (15561): #9      _Encryption.parse
package:rop_sdk/private/cfg_manager.dart:803
I/flutter (15561): #10     ConfigManager.reloadData.parseContent
package:rop_sdk/private/cfg_manager.dart:286
I/flutter (15561): #11     ConfigManager.reloadData.parseContent
package:rop_sdk/private/cfg_manager.dart:283
I/flutter (15561): #12     ConfigManager.reloadData
```

I use golang's standard library to encode this file with gzip encoding. It's not a rare case. I could run into this several times in a month.

**Comment by brendan-duncan** [comment]
I'll try to look into this soon. I know I said that before, but time keeps disappearing. If nothing else, I should be able to have it gracefully discard the seemingly bad data in the huffman block.

**Comment by rockingdice** [comment]
@brendan-duncan it's really nice to get your reply. I've been using this package for a LONG time, it's unique for flutter since the package is working on all platforms and is well-maintained.

**Comment by brendan-duncan** [comment]
I seemed to have fixed the Inflate function to not have the out of bounds problem and it decompresses the provided file correctly now. I'll do some testing and get the fix out shortly.

**Comment by brendan-duncan** [comment]
I published the fix to 3.3.1. I'll close the issue since I **think** I fixed it, but if it's still broken, feel free to re-open or make a new issue.

**Comment by rockingdice** [comment]
Thank you for this quick fix!!

**Comment by husainazkas** [comment]
Hello, I found similar issue at latest version. Could you fix this too? @brendan-duncan 

Log error is just shows `flutter: RangeError (index): Index out of range: index should be less than 286: 286`
I use `extractFileToDisk` method to extract compressed zip with password.

Thanks for every contributors.
