### ISSUE TITLE
Index out of range: index should be less than 272: 272

### ISSUE THREAD

**Issue by corbindavenport** [brendan-duncan/archive#186]
Archive seems to error out when used with this Android SDK zip package from Google: https://dl.google.com/android/repository/platform-tools_r32.0.0-linux.zip

This is my code (full version [here](https://github.com/corbindavenport/nexus-tools/blob/a3948d5b19b1d6b58124b61294403ac993270e82/bin/main.dart)):
```
var net = Uri.parse("https://dl.google.com/android/repository/platform-tools_r32.0.0-linux.zip");
var data = await http.readBytes(net);
var archive = ZipDecoder().decodeBytes(data);
extractArchiveToDisk(archive, "/home/corbin/.nexustools");
```
Here's the error:
```
Unhandled exception:
RangeError (index): Index out of range: index should be less than 272: 272
#0      Uint8List.[]= (dart:typed_data-patch/typed_data_patch.dart:2251:7)
#1      Inflate._decode (package:archive/src/zlib/inflate.dart:306:20)
#2      Inflate._parseDynamicHuffmanBlock (package:archive/src/zlib/inflate.dart:235:20)
#3      Inflate._parseBlock (package:archive/src/zlib/inflate.dart:122:9)
#4      Inflate._inflate (package:archive/src/zlib/inflate.dart:92:20)
#5      new Inflate.buffer (package:archive/src/zlib/inflate.dart:22:5)
#6      ArchiveFile.decompress (package:archive/src/archive_file.dart:81:28)
#7      ArchiveFile.content (package:archive/src/archive_file.dart:67:7)
#8      extractArchiveToDisk (package:archive/src/io/extract_archive_to_disk.dart:29:29)
#9      installPlatformTools (file:///home/corbin/Documents/nexus-tools/bin/main.dart:76:3)
<asynchronous suspension>
#10     main (file:///home/corbin/Documents/nexus-tools/bin/main.dart:295:5)
<asynchronous suspension>
```

Tested on Dart 2.16.0 on a Linux host, archive version 3.1.11.

**Comment by brendan-duncan** [comment]
I recently made a bunch of changes to extractArchiveToDisk in the main branch. I just tested it against that and it extracts correctly. I'll be pushing those changes soon to a new version soon.

**Comment by corbindavenport** [comment]
Looks like this is fixed now, thanks!
