### ISSUE TITLE
archive 3.2.1 introduces a regression on spreadsheet_decoder

### ISSUE THREAD

**Issue by sestegra** [brendan-duncan/archive#193]
After upgrading from 3.2.0 to 3.2.1, following error is found on [spreadsheet_decoder](https://github.com/sestegra/spreadsheet_decoder) package.

```
Unhandled exception:
type 'Null' is not a subtype of type 'List<int>' in type cast
#0      ZipEncoder.getFileCrc32 (package:archive/src/zip_encoder.dart:91:34)
#1      ZipEncoder.addFile (package:archive/src/zip_encoder.dart:136:15)
#2      ZipEncoder.encode (package:archive/src/zip_encoder.dart:65:7)
#3      SpreadsheetDecoder.encode (package:spreadsheet_decoder/src/spreadsheet.dart:176:25)
#4      main (file:///Users/stephane.este-gracias/repos/sestegra/dart/spreadsheet_decoder/example/spreadsheet_decoder.dart:34:32)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

See related issue
https://github.com/sestegra/spreadsheet_decoder/issues/35

**Comment by brendan-duncan** [comment]
Thanks for letting me know, I will look into it.

**Comment by sestegra** [comment]
The issue appears from 3.1.x to 3.2.0.

**Comment by sestegra** [comment]
@brendan-duncan I found the root cause.

https://github.com/brendan-duncan/archive/commit/e9955c37227834e4367e750e3649d34e36ddb747#diff-8cf025b6f411b88d1e7911cb07765976f4f5f284b634342eeab10b342dbf75c9L36

`List<int>` isn't supported by `ArchiveFile` constructor anymore.

**Comment by brendan-duncan** [comment]
Great, thanks for helping figure that out. I'll make that a bit more robust for other incoming data types.

**Comment by sestegra** [comment]
On my side, I can remove the following cast as well.
https://github.com/sestegra/spreadsheet_decoder/blob/master/lib/src/spreadsheet.dart#L194

**Comment by brendan-duncan** [comment]
It'll be a lot more efficient for you to not have that cast anyways. List<int> was used before because it's an abstract class, which Uint8List implements, not because it expected a concrete List<int>. 

I'll still update the constructor to be more robust, and handle things like other buffer/array types.

**Comment by brendan-duncan** [comment]
Dart did make List and the typed_arrays confusing, where List is both an abstract class, and a concrete type.

**Comment by brendan-duncan** [comment]
I pushed a commit to git that re-adds List<int>, and adds content type for all TypedData lists (Float32List, etc), and String data.
