### ISSUE TITLE
Zip extraction causing index out of range.

### ISSUE THREAD

**Issue by fz3hra** [brendan-duncan/archive#264]
Hello everyone, I am actually receiving some data which is in base64 format from the backend.

However when zipping then unzipping the file which consists of base64 (which is in the form of some images and html files), I am unable to bypass the decodeBytes as it throws me an error of index out of range.

I believe that the content of the files should be in a folder then this folder zipped. 

However I am unable to do that due to my base64 data coming from the backend as individual files.

Can anyone please help me find a way around this?

Thank you so much

**Comment by fz3hra** [comment]
please note that each files in the zip file has a password

**Comment by mudlee** [comment]
I experience the same problem as of today with the same versions.

My code:
```dart
final archive = ZipDecoder().decodeBuffer(InputFileStream(zip.path!), password: password);
```

Error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Value not in range: -15326
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5231:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1936:5)
#2      new Uint8List.view (dart:typed_data:883:19)
#3      OutputStream.subset (package:archive/src/util/output_stream.dart:170:22)
#4      Inflate._decodeHuffman (package:archive/src/zlib/inflate.dart:319:34)
#5      Inflate._parseFixedHuffmanBlock (package:archive/src/zlib/inflate.dart:214:12)
#6      Inflate._parseBlock (package:archive/src/zlib/inflate.dart:119:13)
#7      Inflate._inflate (package:archive/src/zlib/inflate.dart:91:12)
```

**Comment by fz3hra** [comment]
@mudlee were u able to find a work about please?

**Comment by coseeanna** [comment]
Any updates?
It works for me with version 3.6.1, but not with version 4.0.0 or higher

**Comment by quoc-huynh-cosee** [comment]
I'm encountering the same error with version 4.0.7
