### ISSUE TITLE
ZipDecoder() doesn't support empty zip files

### ISSUE THREAD

**Issue by nex3** [brendan-duncan/archive#75]
The following code:

```dart
import 'package:archive/archive.dart';

void main() {
  ZipDecoder().decodeBytes(ZipEncoder().encode(Archive()));
}
```

produces 

```
Unhandled exception:
ArchiveException: Could not find End of Central Directory Record
#0      ZipDirectory._findSignature (package:archive/src/zip/zip_directory.dart:146:5)
#1      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:28:20)
#2      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:21:30)
#3      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:15:12)
#4      main (file:///home/nweiz/pkg/test_descriptor/test.dart:4:16)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

This also happens when passing bytes from an empty zip file created elsewhere, so I'm pretty sure it's a problem in `ZipDecoder()` and not `ZipEncoder()`.

**Comment by brendan-duncan** [comment]
On the case.

**Comment by brendan-duncan** [comment]
Fixed in https://github.com/brendan-duncan/archive/commit/e9f72e15c3673f1b5e0e1a7f6ba234fc02861dfa

**Comment by brendan-duncan** [comment]
This is been pushed into version 2.0.10.
