### ISSUE TITLE
TarFile.encode() crashes unhelpfully without mode or lastModTime

### ISSUE THREAD

**Issue by nex3** [brendan-duncan/archive#76]
The following code:

```dart
import 'dart:convert';

import 'package:archive/archive.dart';

void main() {
  TarEncoder().encode(Archive()
      ..addFile(ArchiveFile("file.txt", 1, [100])));
}
```

produces this error:

```
Unhandled exception:
NoSuchMethodError: The method 'toRadixString' was called on null.
Receiver: null
Tried calling: toRadixString(8)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      TarFile._writeInt (package:archive/src/tar/tar_file.dart:225:22)
#2      TarFile.write (package:archive/src/tar/tar_file.dart:138:5)
#3      TarEncoder.add (package:archive/src/tar_encoder.dart:52:8)
#4      TarEncoder.encode (package:archive/src/tar_encoder.dart:14:7)
#5      main (file:///home/nweiz/pkg/test_descriptor/test.dart:7:16)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

This can be fixed by setting the `mode` and `lastModTime` fields on the `ArchiveFile`. It seems like `mode` and `lastModeTime` should be optional, and if they aren't a clearer error message and clearer documentation would be helpful.

**Comment by brendan-duncan** [comment]
I wish Dart had Swift-style optionals syntax? Everything being nullable makes it so easy to forget that everything is potentially a null.

**Comment by brendan-duncan** [comment]
Fixed in https://github.com/brendan-duncan/archive/commit/f0388151611f1e6bc68c8799ce388e0da286d3c6

**Comment by brendan-duncan** [comment]
This is been pushed into version 2.0.10.
